---
- name: ensure postgres is installed
  apt: >
    pkg={{item}}
    state=installed
    install_recommends=yes
    update-cache=yes
  become: true
  with_items:
      - postgresql
      - postgresql-contrib
      - postgis
      - postgis-doc
      - python-psycopg2

- name: do upgrades to newly installed postgresql and postgis packages
  apt: upgrade=dist
  become: true

- name: create postgresql user
  postgresql_user: >
    user={{dbuser}} password={{dbpassword}}
    role_attr_flags=LOGIN,CREATEDB,SUPERUSER
  sudo_user: postgres

- name: ensure database is created
  postgresql_db: >
    db={{dbname}}
    login_password={{dbpassword}}
    encoding='UTF-8'
    lc_ctype='en_US.UTF-8'
    lc_collate='en_US.UTF-8'
  sudo_user: postgres
  register: db_created

- name: create postgis extension in db
  command: psql -c "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology; CREATE EXTENSION fuzzystrmatch;  CREATE EXTENSION postgis_tiger_geocoder;" --dbname={{dbname}}
  sudo_user: postgres
  when: db_created.changed

- name: ensure user has access to database
  sudo_user: postgres
  postgresql_user: db={{dbname}} user={{dbuser}} password={{dbpassword}} priv=ALL




