---

# basic system tasks

- name: set locale to {{locale}}
  action: command /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
  sudo: yes

- name: get tomcat packages for geoserver
  apt: name={{item}} state=latest install_recommends=yes update_cache=yes
  sudo: yes
  with_items:
    - build-essential
    - unzip
    - tomcat7
    - tomcat7-admin
    - tomcat7-docs 
    - tomcat7-admin 
    - tomcat7-examples
    - git
    - ant
    - default-jdk

# just tomcat things

- name: create tomcat_users.xml from template
  template: src=tomcat_users.xml.j2 dest=/etc/tomcat7/tomcat_users.xml owner=root group=root mode=0644
  sudo: yes