---
- hosts: all
  sudo : yes
  vars_files:
    - vars.yml
  roles:
    - common

- hosts: all
  sudo: yes
  vars_files:
    - vars.yml
  roles:
    - dbserver
    - webserver

- hosts: all
  sudo: yes
  vars_files:
    - vars.yml
  roles:
    - geoserver
