---

- name: set locale to {{locale}}
  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
  become: true

- name: add postgresql repos
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present
  become: true

- name: add postgresql repo key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  become: true

- name: install required system packages.
  apt: pkg={{item}} state=installed install_recommends=yes update-cache=yes
  become: true
  with_items:
      - apt-file
      - build-essential
      - python-setuptools
      - python-pip
      - virtualenvwrapper
      - supervisor
      - python-apt
      - python-pycurl
      - python-software-properties
      - python-virtualenv
      - python-dev
      - vim
      - libpq-dev
      - supervisor
      - python-psycopg2
      - git
      - gdal-bin
      - postgresql
      - postgresql-contrib
      - postgis
      - postgis-doc

- name: do upgrades to newly installed packages
  action: apt upgrade=yes
  become: true

# - name: Download spf13 vim install script
#   command: curl http://j.mp/spf13-vim3 -L -o /vagrant/{{ spf13_output_file_name }}
#   when: spf13fileexists is not defined
#   register: spf13fileexists
#
# - name: launch spf13 install script
#   command: sh /vagrant/{{ spf13_output_file_name }}
#   become: true
#   register: spf13installed
#   when: spf13installed is not defined


